<a href="https://colab.research.google.com/github/pawtar90/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

1D Array

In [5]:
x = np.array([1 , 3])
print(x)
type(x)

[1 3]


numpy.ndarray

In [6]:
x.ndim

1

In [7]:
x.size

2

In [8]:
x.shape

(2,)

In [9]:
x.dtype

dtype('int64')

In [10]:
x=np.array([1.3, 2.3, 1.4])
print(x)
x.dtype

[1.3 2.3 1.4]


dtype('float64')

2D Array


In [11]:
x=np.array([[1, 2], [-3,1]])
x.ndim

2

In [12]:
x.shape

(2, 2)

In [13]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [14]:
x.shape

(2, 3)

3D Array

In [15]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
      [4,2,1]],
     
     [[3,2,1],
      [4,1,2]]]



)
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]

 [[3 2 1]
  [4 1 2]]]


In [16]:
x.ndim

3

In [17]:
x.shape

(3, 2, 3)

# typy danych

In [18]:
A = np.array([1, 2, 3], dtype ='float')
A.dtype

dtype('float64')

In [19]:
A = np.array([100, 145, 200], dtype=np.uint8)
A.dtype

dtype('uint8')

# tworzenie tablicy


In [20]:
A = np.zeros(shape=(4,10))
A 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
 np.full(shape=(3,3),fill_value=4,dtype='int')
 

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [25]:
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Operacje na tablicach

In [29]:
A = np.array([3, 1, 4, 2])
B= np.array([3, -1, 3 ,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [30]:
A+B

array([6, 0, 7, 4])

In [31]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [32]:
abs(B)

array([3, 1, 3, 2])

In [33]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6,0], [-1,2]])
print(X)

print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [34]:
X*Y

array([[6, 0],
       [2, 0]])

In [35]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [36]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [37]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

# generowanie liczb pseudolosowych


In [38]:
np.random.seed(0)

In [39]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [40]:
np.random.rand()
np.random.rand(10,4)

array([[0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077, 0.57019677]])

In [41]:
np.random.randint(low=10,high=100)

94

In [42]:
np.random.choice([4 , 2 , 1, 2])

2

In [43]:
np.random.choice(['pythom','java','sql'])

'pythom'

In [44]:
data = np.arange(10)

In [45]:
np.random.shuffle(data)


In [46]:
data

array([1, 2, 5, 0, 9, 3, 8, 7, 4, 6])

# podstawower funkcje


In [47]:
np.exp(1)

2.718281828459045

In [48]:
np.all([2,3,1])

True

In [49]:
np.any([1 ,2 ,1])

True

In [50]:
np.any([0,0,0])

False

In [51]:
bool(0)

False

In [52]:
 A = np.random.rand(5)

In [53]:
A

array([0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [54]:
np.argmax(A)

4

In [55]:
A[np.argmax(A)]


0.6747523222590207

In [56]:
np.argsort(A)

array([3, 0, 1, 2, 4])

In [57]:
np.mean(A)

0.5050672257489125

# indeskowanie wycinanie, iteracje, rozmiary, maski




In [58]:
A = np.arange(20)

In [60]:
# A[idx]; A[start:stop]; A[:stop], A[start:]

In [63]:
A[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
A[0]

array([0, 1, 2, 3, 4])

In [73]:
A[:,-1]

array([ 4,  9, 14, 19])

In [75]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [77]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [79]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [80]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [81]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [83]:
for col in A.T:
  print(col)

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [85]:
A = np.arange(start=-10,stop=10,step=0.5)
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [86]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [87]:
A[A>0]


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [88]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [89]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])