<a href="https://colab.research.google.com/github/pawtar90/data-science-bootcamp/blob/main/01_wprowadzenie/02_algerba_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([0,4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)

4.0

In [4]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [5]:
p = np.array([3,0])
q=np.array([0,4])
np.linalg.norm(p-q)

5.0

In [6]:
p = np.array([3,0,1])
q=np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [8]:
X = np.array([[2, -1, 3 ],
              [3, 1, 0]])
Y=np.array([[2, 1, -1],
            [0, -1, 2],
            [3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [9]:
X.dot(Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [10]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [11]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [14]:
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [20]:
A=np.array([[2,4],
            [1, -1]])
B=np.array([[10],[-1]]);
A_inv = np.linalg.inv(A)
x = np.dot(A_inv,B)
x

array([[1.],
       [2.]])